Areas/Admin/Controllers/CountSummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BayTreasureChestAssociation.Data;
using BayTreasureChestAssociation.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BayTreasureChestAssociation.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrator,Editor,ReadOnly")]
    public class CountSummaryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CountSummaryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Edit()
        {
            List<Draw> draws = _db.Draws.ToList();
            List<WinnerLog> winnerLogs = _db.WinnerLogs.ToList();
            List<CalendarDate> calendarDates = _db.CalendarDates.ToList();
            List<Registration> registrations = _db.Registrations.ToList();
            List<Player> players = _db.Players.ToList();
            // sort the draws by date
            if (draws != null)
            {
                draws.Sort((a, b) =>
                {
                    if (a.CalendarDateID > b.CalendarDateID)
                    {
                        return -1;
                    }
                    if (a.CalendarDateID < b.CalendarDateID)
                    {
                        return 1;
                    }
                    return 0;
                });
                // get the latest draw and add it to the summary sheet model
                Draw draw = draws[0];
                DrawSummarySheet drawSummarySheet = new DrawSummarySheet();
                drawSummarySheet.Draw = draw;
                // get the winner log for that draw and add it to the summary sheet model
                WinnerLog winnerLog = (from wl in winnerLogs
                                       where wl.DrawID == draw.Id
                                       select wl).FirstOrDefault();
                drawSummarySheet.WinnerLog = winnerLog;

                // set the locations list
                drawSummarySheet.Locations = _db.Locations.ToList();
                // get the calendar date and add it to the model
                drawSummarySheet.CalendarDate = (from cd in calendarDates
                                                 where cd.Id == draw.CalendarDateID
                                                 select cd).FirstOrDefault();
                // get the registration and add it to the model
                drawSummarySheet.Registration = (from r in registrations
                                                 where r.Id == draw.RegistrationID
                                                 select r).FirstOrDefault();
                // get the player and add it to the model
                drawSummarySheet.Player = (from p in players
                                           where p.Id == drawSummarySheet.Registration.PlayerId
                                           select p).FirstOrDefault();
                if (drawSummarySheet.Player != null)
                {
                    if (string.IsNullOrEmpty(drawSummarySheet.Player.Address)) drawSummarySheet.Player.Address = "Not Recorded.";
                    if (string.IsNullOrEmpty(drawSummarySheet.Player.Community)) drawSummarySheet.Player.Community = "Not Recorded.";
                }
                // pass the model to the view
                return View(drawSummarySheet);
            }
            // pass an empty model to the view
            return View(new DrawSummarySheet());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Editor")]
        public async Task<IActionResult> Edit(DrawSummarySheet drawSummarySheet)
        {
            Draw drawFromDb = _db.Draws.Find(drawSummarySheet.Draw.Id);
            drawFromDb.BareCoins = drawSummarySheet.Draw.BareCoins;
            drawFromDb.CalendarDate = _db.CalendarDates.Where(cd => cd.Id == drawSummarySheet.CalendarDate.Id).FirstOrDefault();
            drawFromDb.CalendarDateID = drawSummarySheet.CalendarDate.Id;
            drawFromDb.Comments = drawSummarySheet.Draw.Comments;
            drawFromDb.DisqualifiedPinkSheetStickers = drawSummarySheet.Draw.DisqualifiedPinkSheetStickers;
            drawFromDb.ExpectedStickerCount = drawSummarySheet.Draw.ExpectedStickerCount;
            drawFromDb.HasWinner = drawSummarySheet.Draw.HasWinner;
            drawFromDb.KnownVariance = drawSummarySheet.Draw.KnownVariance;
            drawFromDb.NewRegistrations = drawSummarySheet.Draw.NewRegistrations;
            Registration reg = _db.Registrations.Where(r => r.Id == drawSummarySheet.Registration.Id).FirstOrDefault();
            drawFromDb.Registration = reg;
            drawFromDb.RegistrationID = reg.Id;
            drawFromDb.StickerCount = drawSummarySheet.Draw.StickerCount;
            drawFromDb.Supervisor = drawSummarySheet.Draw.Supervisor;
            drawFromDb.TotalStickerCount = drawSummarySheet.Draw.TotalStickerCount;
            drawFromDb.UnderStickeredDollarBills = drawSummarySheet.Draw.UnderStickeredDollarBills;
            drawFromDb.UnknownStickerCount = drawSummarySheet.Draw.UnknownStickerCount;
            _db.Update(drawFromDb);
            WinnerLog winnerLogFromDb = _db.WinnerLogs.Find(drawSummarySheet.WinnerLog.Id);
            winnerLogFromDb.Draw = _db.Draws.Find(drawSummarySheet.Draw.Id);
            winnerLogFromDb.DrawID = winnerLogFromDb.Draw.Id;
            winnerLogFromDb.RolloverAmount = drawSummarySheet.WinnerLog.RolloverAmount;
            winnerLogFromDb.RolloverCount = drawSummarySheet.WinnerLog.RolloverCount;
            winnerLogFromDb.WasPlayed = drawSummarySheet.WinnerLog.WasPlayed;
            winnerLogFromDb.ActualPrize = drawSummarySheet.WinnerLog.ActualPrize;
            winnerLogFromDb.BankDeposit = drawSummarySheet.WinnerLog.BankDeposit;
            winnerLogFromDb.ChequeNumber = drawSummarySheet.WinnerLog.ChequeNumber;
            winnerLogFromDb.Comments = drawSummarySheet.WinnerLog.Comments;
            winnerLogFromDb.Draw = drawFromDb;
            winnerLogFromDb.DrawID = drawFromDb.Id;
            winnerLogFromDb.HasRollover = drawSummarySheet.WinnerLog.HasRollover;
            winnerLogFromDb.LocationPlayed = drawSummarySheet.WinnerLog.LocationPlayed;
            winnerLogFromDb.PossiblePrize = drawSummarySheet.WinnerLog.PossiblePrize;
            winnerLogFromDb.RolloverAmount = drawSummarySheet.WinnerLog.RolloverAmount;
            winnerLogFromDb.RolloverCount = drawSummarySheet.WinnerLog.RolloverCount;
            if (!drawSummarySheet.Draw.HasWinner)
            {
                if (_db.WinnerLogs.Count() > 0)
                {
                    if (winnerLogFromDb.DrawID > 1)
                    {
                        WinnerLog previousLog = FindPreviousWinnerLog(drawFromDb.CalendarDate);
                        if (previousLog != null) winnerLogFromDb.RolloverCount = previousLog.RolloverCount + 1;
                    }
                }
                else
                    winnerLogFromDb.RolloverCount = 1;
            }
            _db.Update(winnerLogFromDb);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(GetSummarySheetList));
        }

        [Authorize(Roles = "Administrator,Editor")]
        public IActionResult EditSheetFields(int id)
        {
            Draw draw = _db.Draws.Find(id);
            DrawUpdate drawUpdate = new DrawUpdate()
            {
                Comments = draw.Comments,
                DrawId = draw.Id,
                StickerCount = draw.StickerCount
            };
            return View(drawUpdate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Editor")]
        public async Task<IActionResult> EditSheetFields(int id, DrawUpdate drawUpdate)
        {
            Draw draw = _db.Draws.Find(id);
            draw.Comments = drawUpdate.Comments;
            draw.StickerCount = drawUpdate.StickerCount;
            _db.Update(draw);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(GetSummarySheetList));
        }

        public IActionResult GetSummarySheetList()
        {
            List<DrawSummarySheet> sheets = new List<DrawSummarySheet>();
            foreach (WinnerLog log in _db.WinnerLogs)
            {
                DrawSummarySheet sheet = new DrawSummarySheet();
                Draw draw = _db.Draws.Find(log.DrawID);
                Registration registration = _db.Registrations.Find(draw.RegistrationID);
                Player player = _db.Players.Find(registration.PlayerId);
                CalendarDate calendarDate = _db.CalendarDates.Find(draw.CalendarDateID);
                sheet.CalendarDate = calendarDate;
                sheet.Draw = draw;
                sheet.Player = player;
                sheet.Registration = registration;
                sheet.WinnerLog = log;
                sheet.Locations = _db.Locations.ToList();
                sheets.Add(sheet);
            }
            return View(sheets);
        }
        private string GetLatestWednesday()
        {
            string lastWednesday = string.Empty;
            DateTime now = DateTime.Now;
            if (now.DayOfWeek == DayOfWeek.Wednesday)
            {
                lastWednesday = now.ToShortDateString();
            }
            else
            {
                // go back a week
                now = now.Subtract(TimeSpan.FromDays(7.0));
                for (int i = 0; i < 7; i++)
                {
                    if (now.DayOfWeek == DayOfWeek.Wednesday)
                    {
                        break;
                    }
                    else
                    {
                        // keep adding days until you find Wednesday
                        now = now.AddDays(1.0);
                    }
                }

Areas/Admin/Views/CountSummary/EditSheetFields.cshtml
@model DrawUpdate
@{
    ViewData["Title"] = "Edit Summary Sheet Fields";
}
<br /><br />
<h2 class="text-info">Edit Summary Sheet Fields</h2>
<br />
<form method="post" asp-action="EditSheetFields">
    <input type="hidden" asp-for="@Model.DrawId" />
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label for="comments">Comments</label>
            </div>
            <div class="col-10">
                <input id="comments" type="text" asp-for="@Model.Comments" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label for="stickerCount">Total Sticker Count</label>
            </div>
            <div class="col-2">
                <input id="stickerCount" asp-for="@Model.StickerCount" type="number" class="form-control" />
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" id="updateButton" class="btn btn-primary" value="Update" />
            <a asp-action="GetSummarySheetList" class="btn btn-success">Back to list</a>
        </div>
    </div>
</form>

Areas/Admin/Views/CountSummary/GetSummarySheetList.cshtml
@model IEnumerable<DrawSummarySheet>
@using BayTreasureChestAssociation.Utilities
@{
    ViewData["Title"] = "Summary Sheet List";
}
<br /><br />
<div class="row">
    <div class="col-6" style="padding-bottom:30px">
        <h2 class="text-info">Count Summary Sheet List</h2><br />
        <span>
            Status Legend:&nbsp;&nbsp;
        </span>
        <span style="font-weight:bolder">
            Active&nbsp;&nbsp;
        </span>
        <span class="bj-retired">
            Retired&nbsp;&nbsp;
        </span>
        <span class="bj-other">
            Other&nbsp;&nbsp;
        </span>
    </div>
</div>



<br />
@{
    if (Model.Count() > 0)
    {
        @if (User.IsInRole(StringValues.AppAdministrator) || User.IsInRole(StringValues.AppEditor))
        {
            <div>
                <a type="button" class="btn btn-warning" href="@Url.Action("Edit", "CountSummary")">
                    Edit Last
                </a>
            </div>
        }

        <br />
        <br />
        <div>
            <table class="table table-striped border" id="drawSheetTable">
                <thead>
                    <tr class="table-info">
                        <th>Draw Date</th>
                        <th>Winner Name</th>
                        <th>Registration Number</th>
                        <th>Bank Deposit ($)</th>
                        <th>Total Prize ($)</th>
                        @if (User.IsInRole(StringValues.AppAdministrator) || User.IsInRole(StringValues.AppEditor))
                        {
                            <th>Actions</th>
                        }

                        <th class="bj-hidden-column">Cheque Number</th>
                        <th class="bj-hidden-column">Supervisor</th>
                        <th class="bj-hidden-column">Rollover Amount</th>
                        <th class="bj-hidden-column">Has Winner</th>
                        <th class="bj-hidden-column">Sticker Count</th>
                        <th class="bj-hidden-column">Expected Sticker Count</th>
                        <th class="bj-hidden-column">Under-Stickered Dollar Bills ($)</th>
                        <th class="bj-hidden-column">Bare Coins ($)</th>
                        <th class="bj-hidden-column">Disqualified Pink Sheet Stickers ($)</th>
                        <th class="bj-hidden-column">Known Variance ($)</th>
                        <th class="bj-hidden-column">New Registrations</th>
                        <th class="bj-hidden-column">Comments</th>
                        <th class="bj-hidden-column">Phone</th>
                        <th class="bj-hidden-column">Email</th>
                        <th class="bj-hidden-column">Address</th>
                        <th class="bj-hidden-column">Player Community</th>
                        <th class="bj-hidden-column">Location Played</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DrawSummarySheet sheet in Model)
                    {
                    <tr>
                        <td>@sheet.CalendarDate.DateStart.ToShortDateString()</td>
                        @if (sheet.Draw.HasWinner)
                        {
                            <td>@sheet.Player.FirstName @sheet.Player.MiddleName @sheet.Player.LastName</td>
                        }
                        else
                        {
                            <td>-- No Winner --</td>
                        }
                        @if (sheet.Registration.Status == "Active")
                        {
                            <td class="bj-active">@sheet.Registration.RegNumber</td>
                        }
                        else if (sheet.Registration.Status == "Retired")
                        {
                            <td class="bj-retired">@sheet.Registration.RegNumber</td>
                        }
                        else
                        {
                            <td class="bj-other">@sheet.Registration.RegNumber</td>
                        }

                        <td>@sheet.WinnerLog.BankDeposit</td>
                        <td>@sheet.WinnerLog.ActualPrize</td>
                        @if (User.IsInRole(StringValues.AppAdministrator) || User.IsInRole(StringValues.AppEditor))
                        {
                            <td>
                                <a type="button" class="btn btn-success" href="@Url.Action("EditSheetFields/"+sheet.Draw.Id)">
                                    <i class="fas fa-edit" title="Update Comments or Sticker Count"></i>
                                </a>
                            </td>
                        }

                        <td class="bj-hidden-column">@sheet.WinnerLog.ChequeNumber</td>
                        <td class="bj-hidden-column">@sheet.Draw.Supervisor</td>
                        <td class="bj-hidden-column">@sheet.WinnerLog.RolloverAmount</td>
                        <td class="bj-hidden-column">@sheet.Draw.HasWinner</td>
                        <td class="bj-hidden-column">@sheet.Draw.StickerCount</td>
                        <td class="bj-hidden-column">@sheet.Draw.ExpectedStickerCount</td>
                        <td class="bj-hidden-column">@sheet.Draw.UnderStickeredDollarBills</td>
                        <td class="bj-hidden-column">@sheet.Draw.BareCoins</td>
                        <td class="bj-hidden-column">@sheet.Draw.DisqualifiedPinkSheetStickers</td>
                        <td class="bj-hidden-column">@sheet.Draw.KnownVariance</td>
                        <td class="bj-hidden-column">@sheet.Draw.NewRegistrations</td>
                        <td class="bj-hidden-column">@sheet.Draw.Comments</td>
                        @if (sheet.Draw.HasWinner)
                        {
                            <td class="bj-hidden-column">@sheet.Player.Phone</td>
                            <td class="bj-hidden-column">@sheet.Player.Email</td>
                            <td class="bj-hidden-column">@sheet.Player.Address</td>
                            <td class="bj-hidden-column">@sheet.Player.Community</td>
                            <td class="bj-hidden-column">@sheet.WinnerLog.LocationPlayed</td>
                        }
                        else
                        {
                            <td class="bj-hidden-column">N/A</td>
                            <td class="bj-hidden-column">N/A</td>
                            <td class="bj-hidden-column">N/A</td>
                            <td class="bj-hidden-column">N/A</td>
                            <td class="bj-hidden-column">N/A</td>
                        }
                    </tr>
                    }
                </tbody>
                <tfoot>
                    <tr class="table-secondary" style="font-weight:bold">
                        <td>Draw Date</td>
                        <td>Winner Name</td>
                        <td>Registration Number</td>
                        <td>Bank Deposit ($)</td>
                        <td>Total Prize ($)</td>
                        @if (User.IsInRole(StringValues.AppAdministrator) || User.IsInRole(StringValues.AppEditor))
                        {
                            <td>Actions</td>
                        }
                        <td class="bj-hidden-column">Cheque Number</td>
                        <td class="bj-hidden-column">Supervisor</td>
                        <td class="bj-hidden-column">Rollover Amount</td>
                        <td class="bj-hidden-column">Has Winner</td>
                        <td class="bj-hidden-column">Sticker Count</td>
                        <td class="bj-hidden-column">Expected Sticker Count</td>
                        <td class="bj-hidden-column">Under-Stickered Dollar Bills ($)</td>
                        <td class="bj-hidden-column">Bare Coins ($)</td>
                        <td class="bj-hidden-column">Disqualified Pink Sheet Stickers ($)</td>
                        <td class="bj-hidden-column">Known Variance ($)</td>
                        <td class="bj-hidden-column">New Registrations</td>
                        <td class="bj-hidden-column">Comments</td>
                        <td class="bj-hidden-column">Phone</td>
                        <td class="bj-hidden-column">Email</td>
                        <td class="bj-hidden-column">Address</td>
                        <td class="bj-hidden-column">Player Community</td>
                        <td class="bj-hidden-column">Location Played</td>
                    </tr>
                </tfoot>
            </table>

            @if (Model.Count() > 0)
            {
                <script type="text/javascript" src="~/js/Custom/MakeDatatable.js"></script>
                @if (User.IsInRole(StringValues.AppAdministrator) || User.IsInRole(StringValues.AppEditor))
                {
                    <script type="text/javascript">
                        $(function () {
                            $('.bj-hidden-column').hide();
                            let tableDiv = 'drawSheetTable';
                            // no need to sort or order hidden columns or action button column
                            let columnDefs = [{
                                "targets": [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
                                "orderable": false,
                                "searchable": false
                            }];
                            let exportOptions = {
                                columns: [0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
                            };
                            let sortedColumns = [[0, "desc"]];
                            makeDatatable(tableDiv, columnDefs, exportOptions, sortedColumns);
                        });
                    </script>
                }
                else
                {
                    <script type="text/javascript">
                        $(function () {
                            $('.bj-hidden-column').hide();
                            let tableDiv = 'drawSheetTable';
                            // no need to sort or order hidden columns or action button column
                            let columnDefs = [{
                                "targets": [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
                                "orderable": false,
                                "searchable": false
                            }];
                            let sortedColumns = [[0, "desc"]];
                            makeNonExportingDatatable(tableDiv, columnDefs, sortedColumns);
                        });
                    </script>
                }
            }
        </div>
    }
}